### ISSUE TITLE
K particle gun request to resolve G3/G4 difference near p 0.5 GeV/c and theta 120 degrees

### ISSUE THREAD

**Issue by nsjarvis** [JeffersonLab/HDGeant4#137] opened 2019-12-18 20:21 UTC
A marked difference between G3 and G4 simulations was seen in the u-channel of the  K+Sigma0 analysis.  With the current analysis, the data look more like G3.  

This was brought up in the 19 Nov HDG4 meeting, the minutes and original presentation are at  https://halldweb.jlab.org/wiki/index.php/HDGeant4_Meeting,_November_19,_2019#Minutes

![image](https://user-images.githubusercontent.com/15655254/71119805-feb94b00-21a8-11ea-94d1-a0a133bf4a26.png)

**Comment by sdobbs** [comment] 2020-05-04 13:14
This should be revisited in light of #149

**Comment by rjones30** [comment] 2020-05-05 14:17
Here is what I see when I look at slow backward K+ tracks in G4, G3(HADR=1) and G3(HADR=4). The output is just what monitoring_hists saves for K+ under Hist_DetectorParticleKinematics. I can remake these histograms with higher resolution if desired, but I think these are adequate.

- K+ particle gun, 0.25 < p < 0.75 GeV, 80 < theta < 140 degrees, run 71500
![image](https://user-images.githubusercontent.com/7832920/81076168-54249900-8eb9-11ea-8fed-df66dd675a9c.png)
![image](https://user-images.githubusercontent.com/7832920/81076201-60a8f180-8eb9-11ea-9a40-cceece63a5f6.png)
![image](https://user-images.githubusercontent.com/7832920/81076238-6c94b380-8eb9-11ea-8b44-80cf9a0da63d.png)

Here are the x and y projections of these plots, shown for comparison in the same plot.
![image](https://user-images.githubusercontent.com/7832920/81076337-8a621880-8eb9-11ea-9121-b4dcfd022580.png)
![image](https://user-images.githubusercontent.com/7832920/81076372-91892680-8eb9-11ea-904e-1baa41b315ab.png)

**Comment by rjones30** [comment] 2020-05-05 14:32
How does the "dip" structure arise in Nilanga's result for G3, and it is consistent with these results? I would say yes. His recoil k+ has a strong theta-momentum correlation. Here is a plot taken from his talk that Naomi references above. This is his U-channel distribution, which is where the dip structure appears.
![image](https://user-images.githubusercontent.com/7832920/81077693-4ff97b00-8ebb-11ea-8adf-1add033d14b8.png)
The y-axis scale is too big to see the correlation at backward angles, but we can presume it is just as strong there as it is in the forward region. That cuts a narrow diagonal swath across the PvsTheta plots that I showed in the previous posting. It is easy to imagine there that a dip might be visible as you cross from the higher-momentum blob forward of 120 degrees to the lower-momentum blob backward of 120 degrees.

**Comment by niwgit** [comment] 2020-05-05 23:29
I made these plots from projecting the p vs theta distribution for K+ in data for events in the u-channel (-u < 2.0 GeV^2).
The momentum and theta plots in data does seem to behave somewhat similar to G3.
-Nilanga
[KSigma_u_channel_data_kp_momentum.pdf](https://github.com/JeffersonLab/HDGeant4/files/4584122/KSigma_u_channel_data_kp_momentum.pdf)
[KSigma_u_channel_data_kp_theta.pdf](https://github.com/JeffersonLab/HDGeant4/files/4584124/KSigma_u_channel_data_kp_theta.pdf)

**Comment by rjones30** [comment] 2020-05-06 11:32
It seems that this cutoff around 120degrees might be related to tracking at backward angles. Here is another plot from monitoring_hists that suggests this is happening.
![Screenshot 2020-05-06 at 7 25 26 AM](https://user-images.githubusercontent.com/7832920/81171870-30219000-8f6b-11ea-9a05-b715e92f1b99.png)
I looked in hdview2 at several events where I generated 0.6 GeV/c k+ tracks at 125o. These tracks looked fine visually at the DTrackWireBased and DTrackTimeBased level in hdview with >20 straw hits assigned to the track, but they had very low FOM values for all of the mass hypotheses, including k+, and no DTrackTimeBased:Combos were created.

I will report this to the tracking experts and ask them to look into this. If there is a critical angle where the tracking is breaking down then it is possible that small differences between G3 and G4 are being amplified by the sharpness of the cutoff of the acceptance in the CDC. If so then there might also be a big difference between G3(HADR=1) and G3(HADR=4).

**Comment by zihlmann** [comment] 2020-05-06 12:21
advice for beginners like me, whats the magic comand to look had hddm 
rest files with hdview?
here the error I get for being naive.

hdview2 kstudyrec3_600.hddm
Error in <TCling::RegisterModule>: cannot find dictionary module 
hdv_fulllistframe_Dict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module 
hdv_optionsframe_Dict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module 
hdv_endviewBframe_Dict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module 
hdv_endviewAframe_Dict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module 
hdv_mainframe_Dict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module 
trk_mainframe_Dict_rdict.pcm
Error in <TCling::RegisterModule>: cannot find dictionary module 
hdv_debugerframe_Dict_rdict.pcm
JANA >>Opening source "kstudyrec3_600.hddm" of type: HDDM
terminate called after throwing an instance of 'std::runtime_error'
   what():  Unexpected header found in input HDDM stream: <HDDM 
class="r" version="1.1.0" 
xmlns="http://www.gluex.org/hddm">kstudyrec3_600.hddm
Abort

**Comment by nsjarvis** [comment] 2020-05-06 13:10
Here's a plot of real CDC dE/dx vs theta. 

![cdcdedxthetarun50932](https://user-images.githubusercontent.com/15655254/81180563-34ed4080-8f79-11ea-91bc-3b10fff0bfea.png)

**Comment by sdobbs** [comment] 2020-05-06 14:25
Beni, it looks like our HDDM format guessing is not working perfectly - you can put the string "rest" in the file name, for example, rename the file to "kstudyrec3_rest_600.hddm"

**Comment by rjones30** [comment] 2020-05-06 14:49
Beni,

Hmm, not sure. On the UConn cluster that command works just as you issued
it. Is your environment correctly configured for JANA?

-Richard

**Comment by nsjarvis** [comment] 2020-05-06 15:27
Nilanga, 

the files that you attached yesterday don't seem to be accessible.  The filenames were  KSigma_u_channel_data_kp_momentum.pdf and 
KSigma_u_channel_data_kp_theta.pdf.

Could you try uploading the plots as png images instead, please?

**Comment by niwgit** [comment] 2020-05-06 15:46
I'll try uploading as png.
![KSigma_u_channel_data_kp_momentum](https://user-images.githubusercontent.com/23059941/81198073-109c5e80-8f8f-11ea-8362-375b1a4906a7.png)
![KSigma_u_channel_data_kp_theta](https://user-images.githubusercontent.com/23059941/81198089-14c87c00-8f8f-11ea-8766-72ab808a4d5d.png)

**Comment by rjones30** [comment] 2020-05-07 09:46
I took the k+ generated kinematics shared by Nilanga and generated 3 samples of 1M events each, one with hdgeant4, one with hdgeant(HADR=1) and one with hdgeant(HADR=4). Here is the reconstructed p vs theta 2d plot from the hdgeant4 sample.
![image](https://user-images.githubusercontent.com/7832920/81279545-49871280-9025-11ea-87fc-a4afd8f45d6d.png)
All three of these plots look the same. The x and y projections are more useful, since this is really a 1d distribution.
![image](https://user-images.githubusercontent.com/7832920/81279674-73403980-9025-11ea-8099-fef97a9fff6e.png)
![image](https://user-images.githubusercontent.com/7832920/81279715-7f2bfb80-9025-11ea-9fd0-e06effea5023.png)
The dip structure is seen in all three samples, with slight differences between them, but nothing that would make G4 stand out from G3. In fact, G4 seems to be intermediate between the two G3 models. I see nothing here to suggest a problem with the simulation. There are probably issues with the PID at backward angles that are not well understood because u-channel processes have not been looked at much so far in GlueX.

**Comment by rjones30** [comment] 2020-05-07 09:57
To rule out the possibility that the blob structure might be coming from a bug in the geometry that affects all 3 simulations, I produced REST output from the earlier particle gun samples and plot all of the time-based tracks that are reconstructed as kaons. There is no FOM cut here. The first plot is generated, followed by reconstructed G4, G3(HADR=1), and G3(HADR=4). These plots suggest that the tracking is working just fine. I conclude from this that the blobs are coming from some combination of timing chisquare cuts and other PID algorithm issues, eg. competition between k+ and proton hypotheses leaning the wrong way in certain regions. 
![image](https://user-images.githubusercontent.com/7832920/81281186-7fc59180-9027-11ea-9c7f-1bb0eeecc0ca.png)
![image](https://user-images.githubusercontent.com/7832920/81281216-894ef980-9027-11ea-9de1-cce26589d048.png)
![image](https://user-images.githubusercontent.com/7832920/81281266-9c61c980-9027-11ea-8568-e352f5416a1b.png)
![image](https://user-images.githubusercontent.com/7832920/81281287-a4216e00-9027-11ea-8744-53ac9133c030.png)

**Comment by rjones30** [comment] 2020-05-07 10:03
Based on the above, I conclude that there is no evidence of misbehavior in the simulations underlying this issue. There are structures in the PvsTheta plots that arise from analysis CUTS that are not seen in the REST data at the level of time-based tracks. This might be related to timing in the BCAL, but if so looking at these high-level plots is not the best way to study it. If these arguments survive review by Nilanga, Noami and others, I suggest that this issue can be closed.

**Comment by zihlmann** [comment] 2020-05-07 11:07
..... and the issue opened in halld_recon.

**Comment by nsjarvis** [comment] 2020-05-07 11:15
I agree.  This issue was to investigate differences between the Geant versions.  Thank you.

**Comment by niwgit** [comment] 2020-05-07 11:46
Thanks Richard,  I missed the point what caused the reconstructed plots from my G4 simulation looks much more like thrown.
Could you clarify please?

**Comment by markdalton** [comment] 2020-05-07 11:53
There was a bug in hdgeant4 which has been fixed.  You should use the latest code, comment out the CUTS card in control.in and do 3 simulations G4, G3(HADR=1) and G3(HADR=4) and check that they produce the same result.

**Comment by jrstevenjlab** [comment] 2020-05-07 11:58
Since we're generally interested in the differences between detector response for samples from G3/G4, especially after the CUTS card removal, it would be good to see the new timing distributions for these tracks to see how sensitive our cuts are.  This would be analogous to the request I made to Colin to reproduce his DeltaT plots https://github.com/JeffersonLab/HDGeant4/issues/111#issuecomment-579437648 with the CUTS card now off.

Richard, could you post the histogram files from the monitoring_hists plugin you've already run, so Nilanga could post plots of Independent/Hist_DetectorPID/BCAL/DeltaTVsP_K+ and compare with his timing distributions from data?

**Comment by niwgit** [comment] 2020-05-07 12:01
Thanks for the clarification Mark.

**Comment by rjones30** [comment] 2020-05-07 12:22
Here are the monitoring_plots histograms for the 8 samples that I have run so far, for easy reference. The studies are:
0: k- particle gun, 0.45<p<0.55 GeV/c, 80o<𝜃<100o, 𝜙=180o
1: k- particle gun, 0.10<p<0.90 GeV/c, 80o<𝜃<100o, 𝜙=180o
2: k- particle gun, 0.25<p<0.85 GeV/c, 5o<𝜃<75o, all 𝜙
3: k- spectrum from recoil Y* decays, generated by Peter Pauli
4: k- particle gun, 0.25<p<0.85 GeV/c, 5o<𝜃<75o, all 𝜙, with CUTS enabled in G4
5: k- particle gun, 0.25<p<0.85 GeV/c, 5o<𝜃<75o, all 𝜙, with CUTS, with G4 fix in place
6:  k+ particle gun, 0.25 < p < 0.75 GeV/c and 80o < 𝜃 < 140o, no CUTS
7: k+ spectrum from u-channel Y* reaction, generated from Nilanga's genr8 spec, no CUTS

Each of these was studied in 3 different runs, tagged by its own suffix.
* hdgeant: suffix=""
* hdgeant (HADR=1): suffix="3"
* hdgeant (HADR=4): suffix="34"

The monitoring_hists output files are available over https at:
https://zeus.phys.uconn.edu/halld/kstudy-4-2020/kstudyrec${suffix}_${sample}xx.root

**Comment by niwgit** [comment] 2020-05-07 18:55
Thanks Richard for the MC root file.
Here are BCAL timing plots for K+. 
Plot for MC is from Independent/Hist_DetectorPID/BCAL/DeltaTVsP_K+
For data it's for the u-channel and for signal region (no accidentals) and from Hist_ParticleID.

![BCAL_delta_t_MC](https://user-images.githubusercontent.com/23059941/81333463-a9f07100-9072-11ea-8307-4ecbb8cbe8d3.png)
![BCAL_delta_t_data](https://user-images.githubusercontent.com/23059941/81333484-afe65200-9072-11ea-811f-98b8ba057fe1.png)

**Comment by niwgit** [comment] 2020-05-07 19:07
Actually the data plot has both signal and accidental regions.

**Comment by rjones30** [comment] 2020-05-07 23:31
It looks like the data have a strict cut on time around the peak at zero delta t. Notice the complete lack of noise over the complete area of the plot. Accidentals subtraction does not do that. The MC does not have such a cut, apparently.

**Comment by niwgit** [comment] 2020-05-07 23:46
The cut in the data must be coming from the default analysis launch cuts.

**Comment by rjones30** [comment] 2020-05-08 05:38
It would be good if you could investigate that.
-Richard

**Comment by sdobbs** [comment] 2020-05-08 14:43
Hi Nilanga, 
If you could please project both of those 2D distributions onto the y axis, this would also be useful to see.

---Sean

**Comment by niwgit** [comment] 2020-05-08 18:46
Hi Sean,
Here are the y-projections from the 2 plots.
-Nilanga

![DeltaT_MC](https://user-images.githubusercontent.com/23059941/81438327-96104200-913a-11ea-86ae-0cc559c15d6d.png)
![DeltaT_data](https://user-images.githubusercontent.com/23059941/81438332-9ad4f600-913a-11ea-802d-e5c2a4010f84.png)

**Comment by rjones30** [comment] 2020-05-08 18:53
Definitely something is cutting into the delta-T plot in real data. These
studies of low-level things (time resolution in the bcal) using a
high-level analysis might not be a great use of your time, Nilanga. There
are too many cuts between you and the simulation to see what is going on.

-Richard Jones

**Comment by sdobbs** [comment] 2020-05-12 23:41
Do we have a volunteer to peel off the backwards track reconstruction/hit matching part of the discussion to a halld_recon issue?

**Closed** 2020-05-26 20:04 UTC
