### ISSUE TITLE
G4 crashes when neutron energy is loo low

### ISSUE THREAD

**Issue by igjaegle** [JeffersonLab/HDGeant4#223] opened 2024-09-30 13:01 UTC
This error seems to have been solved with more recent G4 version
tks ig

The error can be found below. 

G4WT0 >  G4DecayTable::SelectADecayChannel :: no possible DecayChannel       neutron
------- EEEE ------- G4Exception-START -------- EEEE -------
*** G4Exception : DECAY003
      issued by : G4Decay::DoIt
Can not determine decay channel for neutron
  mass of dynamic particle: 0 (GEV)
  dacay table has 1 entries
0: BR 1, IsOK? 0, --> e- + anti_nu_e + proton

*** Fatal Exception *** core dump ***
G4WT0 > G4Track (0x7f66d1207a70) - track ID = 2, parent ID = 0
G4WT0 >  Particle type : neutron - creator process : not available
G4WT0 >  Kinetic energy : 0 eV  - Momentum direction : (0,0,1)
G4WT0 >  Step length : 0 fm  - total energy deposit : 0 eV
G4WT0 >  Pre-step point : (-2.27154e-11,2.38719e-12,564.902) - Physical volume : LASS::1 (LiqDeuterium)
G4WT0 >  - defined by : not available
G4WT0 >  Post-step point : (-2.27154e-11,2.38719e-12,564.902) - Physical volume : LASS::1 (LiqDeuterium)
G4WT0 >  - defined by : not available
G4WT0 >  *** Note: Step information might not be properly updated.
G4WT0 >
-------- EEEE -------- G4Exception-END --------- EEEE -------

G4WT0 >
G4WT0 > *** G4Exception: Aborting execution ***
/group/halld/Software/builds/Linux_CentOS7-x86_64-gcc4.8.5-cntr/gluex_MCwrapper/gluex_MCwrapper-v2.8.1/MakeMC.sh: line 1547: 243254 Aborted                 (core dumped) hdgeant4 -t$NUMTHREADS run.mac

**Comment by rjones30** [comment] 2024-09-30 15:01
Igal, can you set up a directory containing a complete set of files needed
to reproduce the error? Also the versions of the halld software that you
are using. Otherwise, you can mark the issue resolved by a G4 library
upgrade.
-Richard Jones

**Comment by igjaegle** [comment] 2024-09-30 15:08
Thank you, Richard. I will test first the simulation with an upgraded G4 library. If the problem is solved, I will close the issue.

**Comment by rjones30** [comment] 2024-09-30 15:11
Igal, to build hdgeant4 with the updated libraries, after building the new
G4 release and setting up your environment to use it, you need to move the
symbolic link G4fixes in HDGeant4/src to point to the correct patch set,
and then make clean;make.
-Richard

**Comment by aaust** [comment] 2024-10-02 18:36
@rjones30 I started to build a version set based on g4 10.7.2 and Geant4 built without problems:
`/group/halld/Software/builds/Linux_Alma9-x86_64-gcc11.4.1/geant4/geant4.10.07.p04`
 When build_scripts tried to make hdgeant4, it cannot find the `geant4make.sh` script in the `share` folder because the folder does not exist. How did you get around this difference? Can one use the script wih the same name in `data/geant4make/`?

**Comment by rjones30** [comment] 2024-10-02 18:56
You can see my geant4 binary install at /cvmfs/
oasis.opensciencegrid.org/gluex/geant4-v10.7.4/alma9-MT
There the share directory is a symlink to . where the geant4make directory
contains the geant4make.sh script.
This alma9-MT is the installation target of the geant4-v10.7.4.tar.gz
source package installed using the standard
cmake installer with alma9-MT as the INSTALL_PREFIX. I don't remember doing
anything special to get this
installed binary directory structure to show up, but i may have created the
share->. symlink.
-Richard Jones

**Comment by rjones30** [comment] 2024-10-02 22:40
Yes, this is the fix that I introduced in the last PR, remember?
-Richard

**Comment by aaust** [comment] 2024-10-02 23:42
Yes, and the fix worked for the g4.10.4 and root6.24.04 combination. I see this error with g4.10.7 and root6.24.04 now.

**Comment by rjones30** [comment] 2024-10-02 23:45
Looks like the #if for this fix should be switching on the ROOT version,
not the G4 version. Let me have a look. -Richard

**Comment by aaust** [comment] 2024-10-03 14:36
Correct, I was able to build hdgeant4 against g4.10.7 when I reverted the addition of this if statement.
@igjaegle , you may try it with this version set: [version_5.21.1.xml](https://halldweb.jlab.org/halld_versions/version_5.21.1.xml)

**Comment by igjaegle** [comment] 2024-10-05 12:02
The issue is still there after switching to a newer G4 version.

A MCwrapper configuation file can be found here:
/w/halld-scshelf2101/home/gxproj2/gluex_simulations/src-ct-eta-simu-for-2021-11-runs-04102024-rdm-bkg/cfg

Example of error can be found here:
/w/halld-scshelf2101/home/gxproj2/gluex_simulations/src-ct-eta-simu-for-2021-11-runs-04102024-rdm-bkg/deuteron/fix_free_qfn/eta-to-gg

It seems that if I am throwing less than 5k events, the probability of this error happening is so small that all my jobs will succeed.

**Comment by rjones30** [comment] 2024-10-05 12:47
For me to reproduce the error, I ask that you set up a directory with the
following:

   1. a working copy of control.in (not mcwrapper, I understand many people
   use this as an interface but it gets in the way when debugging)
   2. the input event file that reproduces the error
   3. the versions.xml and the container that you are running in (I assume
   the platform is alma9)
   4. a console log from a session showing the error, preferably just the
   input line "hdgeant4" followed by the output with the crash report

-Richard Jones

**Comment by igjaegle** [comment] 2024-10-05 13:51
Richard, you can find the info you asked here:

1 /work/halld/home/ijaegle/public/ForRichard/90595_0/control.in
2 /work/halld/home/ijaegle/public/ForRichard/90595_0/gen_primex_eta_he4_090595_000_decay_evtgen.hddm
3 /work/halld/home/ijaegle/src/gluex/jef/el9/version.xml
No container is used and alma9 is used. This is a copy paste of 5.21.1 but I am using a local halld_recon/sim and hdgeant4. All correspond to master version set.
4 /work/halld/home/ijaegle/public/ForRichard/90595_0/log.txt

**Comment by rjones30** [comment] 2024-10-08 14:16
Thank you for preparing this bug demo. There are bad values in your input file that you are trying to simulate. Here is an example, generated by the command "hddm-xml gen_primex_eta_he4_090595_000_decay_evtgen.hddm | less"
 <physicsEvent eventNo="3565" runNo="90595">
    <reaction type="0" weight="0">
      <beam type="Photon(1)">
        <momentum E="8.32135" px="0" py="0" pz="8.32135" />
        <properties charge="0" mass="0" />
      </beam>
      <target type="Deuteron(45)">
        <momentum E="1.87561" px="0" py="0" pz="0" />
        <properties charge="1" mass="1.87561" />
      </target>
      <vertex>
        <product decayVertex="0" id="1" mech="0" parentid="0" pdgtype="221" type="Unknown(0)">
          <momentum E="8.48872" px="-0.991475" py="1.02541" pz="8.35008" />
        </product>
        <product decayVertex="0" id="2" mech="0" parentid="0" pdgtype="2112" type="Neutron(13)">
          <momentum E="0" px="0" py="0" pz="0" />
        </product>
        <product decayVertex="0" id="3" mech="0" parentid="0" pdgtype="2212" type="Proton(14)">
          <momentum E="0" px="0" py="0" pz="0" />
        </product>

Notice that the total energy E of the neutron is zero. This is also true for the proton, but the neutron is first and so the simulation raises an exception and exits before it seems the bad proton. You cannot assign a neutron E=0. That is the total energy, and for the simulation to work with it you need to satisfy the relation E = (px**2 + py**x + pz**2 + mNeutron**2). Most of your input events respect this, but then every once in a while there are these bogus events like this #3565. Fix your event generator, or run a filter removing these bogus events before feeding them into hdgeant4.

-Richard Jones

**Comment by igjaegle** [comment] 2024-10-21 14:27
You are right, the issue was due to wrong input values

**Comment by igjaegle** [comment] 2024-10-21 14:27
All is good

**Closed** 2024-10-21 14:27 UTC
Labels: bug, duplicate
