### ISSUE TITLE
Differences between G3 and G4 in eta.pi

### ISSUE THREAD

**Issue by cwsalgado** [JeffersonLab/HDGeant4#101] opened 2019-04-04 16:15 UTC
[geantProblem.pdf](https://github.com/JeffersonLab/HDGeant4/files/3044467/geantProblem.pdf)

**Comment by rjones30** [comment] 2019-04-04 17:44
Carlos,

Can you share the generator output hddm file with me, that you are
injecting into hdgeant and hdgeant4?

-Richard

**Comment by cwsalgado** [comment] 2019-04-04 18:48
Hello Richard,

The input file is at:

/w/halld-scifs17exp/halld2/home/salgado/EtaPi-W2MC/eventsW.hddm

That file was produced by genr8_2_hddm. Thank you for your help.

-Carlos

On Apr 4, 2019, at 1:44 PM, Richard Jones <notifications@github.com<mailto:notifications@github.com>> wrote:

Carlos,

Can you share the generator output hddm file with me, that you are
injecting into hdgeant and hdgeant4?

-Richard

**Comment by rjones30** [comment] 2019-04-04 19:28
Carlos,

Ok, got it, will take a look when I get a chance.

-Richard

**Comment by T-Britton** [comment] 2019-04-23 19:51
I believe https://github.com/JeffersonLab/HDGeant4/issues/103 is the culprit.  MCwrapper uses SKIP with input hddm files to ensure that when the project is split each job doesn't run over the same exact events repeatedly.  My hypothesis is that for hdgeant4 the thrown is missing because they were never processed.  Carlos can you rerun both G3 and G4 with only say, 1000 events.  This will keep everything in one single file (SKIP=0) and would be a good way to test whether this is the issue or not

**Comment by T-Britton** [comment] 2019-04-26 18:10
I sat with Carlos and compared the first file produced which is essentially the test I recommended.  I can confirm this is due to the broken SKIP in hdgeant4.  Closing this issue

**Closed by T-Britton** 2019-04-26 18:10 UTC
